export { default as Home } from "./home/Home";
export { default as Contact } from "./contact/Contact";
export { default as Products } from "./products/Products";
export { default as Detail } from "./detail/Detail";
export { default as Login } from "./auth/login/Login";
export { default as Register } from "./auth/register/Register";
export { default as CreateProduct } from "./create/CreateProduct";
export { default as ShoppingCart } from "./shoppingCart/ShoppingCart";
export { default as ProfileUser } from "./profile/ProfileUser";
export { default as CreateUser} from "./createUser/CreateUser";
export { default as CreateAddress} from "./createAddress/CreateAddress";
export { default as EditUser } from "./editUser/EditUser";
export { default as EditAddress } from ".editAddress/EditAddress";
export { default as AdminDashboard } from "./admin/Admin";